simplified sketch_rnn depedencies
I was unable to run sketch_rnn_train.py because of a tangle
of magenta dependencies. Notably, the final error was:

magenta/music/drums_encoder_decoder.py:
  from magenta.music import encoder_decoder
ImportError: cannot import name encoder_decoder

Rather than fall down the rabbit hole, I instead rewired
sketch_rnn to have minimal dependencies.